//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp_for_Self_Hosted_WS.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/BikesServer")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_bike_standsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_bikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contract_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Position positionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bike_stands {
            get {
                return this.available_bike_standsField;
            }
            set {
                if ((this.available_bike_standsField.Equals(value) != true)) {
                    this.available_bike_standsField = value;
                    this.RaisePropertyChanged("available_bike_stands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bikes {
            get {
                return this.available_bikesField;
            }
            set {
                if ((this.available_bikesField.Equals(value) != true)) {
                    this.available_bikesField = value;
                    this.RaisePropertyChanged("available_bikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contract_name {
            get {
                return this.contract_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.contract_nameField, value) != true)) {
                    this.contract_nameField = value;
                    this.RaisePropertyChanged("contract_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Position position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/BikesServer")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStationsElementsProxy")]
    public interface IStationsElementsProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsElementsProxy/GetStations", ReplyAction="http://tempuri.org/IStationsElementsProxy/GetStationsResponse")]
        ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[] GetStations(string CacheItemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsElementsProxy/GetStations", ReplyAction="http://tempuri.org/IStationsElementsProxy/GetStationsResponse")]
        System.Threading.Tasks.Task<ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[]> GetStationsAsync(string CacheItemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsElementsProxy/GeStationstWithSeconds", ReplyAction="http://tempuri.org/IStationsElementsProxy/GeStationstWithSecondsResponse")]
        ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[] GeStationstWithSeconds(string CacheItemName, double dt_seconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsElementsProxy/GeStationstWithSeconds", ReplyAction="http://tempuri.org/IStationsElementsProxy/GeStationstWithSecondsResponse")]
        System.Threading.Tasks.Task<ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[]> GeStationstWithSecondsAsync(string CacheItemName, double dt_seconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsElementsProxy/GeStationstWithOffset", ReplyAction="http://tempuri.org/IStationsElementsProxy/GeStationstWithOffsetResponse")]
        ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[] GeStationstWithOffset(string CacheItemName, System.DateTimeOffset dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsElementsProxy/GeStationstWithOffset", ReplyAction="http://tempuri.org/IStationsElementsProxy/GeStationstWithOffsetResponse")]
        System.Threading.Tasks.Task<ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[]> GeStationstWithOffsetAsync(string CacheItemName, System.DateTimeOffset dt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStationsElementsProxyChannel : ConsoleApp_for_Self_Hosted_WS.ServiceReference1.IStationsElementsProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StationsElementsProxyClient : System.ServiceModel.ClientBase<ConsoleApp_for_Self_Hosted_WS.ServiceReference1.IStationsElementsProxy>, ConsoleApp_for_Self_Hosted_WS.ServiceReference1.IStationsElementsProxy {
        
        public StationsElementsProxyClient() {
        }
        
        public StationsElementsProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StationsElementsProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StationsElementsProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StationsElementsProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[] GetStations(string CacheItemName) {
            return base.Channel.GetStations(CacheItemName);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[]> GetStationsAsync(string CacheItemName) {
            return base.Channel.GetStationsAsync(CacheItemName);
        }
        
        public ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[] GeStationstWithSeconds(string CacheItemName, double dt_seconds) {
            return base.Channel.GeStationstWithSeconds(CacheItemName, dt_seconds);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[]> GeStationstWithSecondsAsync(string CacheItemName, double dt_seconds) {
            return base.Channel.GeStationstWithSecondsAsync(CacheItemName, dt_seconds);
        }
        
        public ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[] GeStationstWithOffset(string CacheItemName, System.DateTimeOffset dt) {
            return base.Channel.GeStationstWithOffset(CacheItemName, dt);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp_for_Self_Hosted_WS.ServiceReference1.Station[]> GeStationstWithOffsetAsync(string CacheItemName, System.DateTimeOffset dt) {
            return base.Channel.GeStationstWithOffsetAsync(CacheItemName, dt);
        }
    }
}
